-- Migration: 001_create_hotel_schema (SQL Server)
SET NOCOUNT ON;

-- DROP tables in reverse order (safe for rebuild in dev)
IF OBJECT_ID('pagamento','U') IS NOT NULL DROP TABLE pagamento;
IF OBJECT_ID('fatura','U') IS NOT NULL DROP TABLE fatura;
IF OBJECT_ID('item_consumo','U') IS NOT NULL DROP TABLE item_consumo;
IF OBJECT_ID('consumo','U') IS NOT NULL DROP TABLE consumo;
IF OBJECT_ID('produto','U') IS NOT NULL DROP TABLE produto;
IF OBJECT_ID('pedido_consumo','U') IS NOT NULL DROP TABLE pedido_consumo;
IF OBJECT_ID('refeicao','U') IS NOT NULL DROP TABLE refeicao;
IF OBJECT_ID('checklist','U') IS NOT NULL DROP TABLE checklist;
IF OBJECT_ID('ordem_limpeza','U') IS NOT NULL DROP TABLE ordem_limpeza;
IF OBJECT_ID('log_acesso','U') IS NOT NULL DROP TABLE log_acesso;
IF OBJECT_ID('credencial_acesso','U') IS NOT NULL DROP TABLE credencial_acesso;
IF OBJECT_ID('estadia','U') IS NOT NULL DROP TABLE estadia;
IF OBJECT_ID('historico_reserva','U') IS NOT NULL DROP TABLE historico_reserva;
IF OBJECT_ID('reserva','U') IS NOT NULL DROP TABLE reserva;
IF OBJECT_ID('quarto','U') IS NOT NULL DROP TABLE quarto;
IF OBJECT_ID('arquivo','U') IS NOT NULL DROP TABLE arquivo;
IF OBJECT_ID('categoria_quarto','U') IS NOT NULL DROP TABLE categoria_quarto;
IF OBJECT_ID('andar','U') IS NOT NULL DROP TABLE andar;
IF OBJECT_ID('dependente','U') IS NOT NULL DROP TABLE dependente;
IF OBJECT_ID('hospede','U') IS NOT NULL DROP TABLE hospede;
IF OBJECT_ID('transacao','U') IS NOT NULL DROP TABLE transacao;
IF OBJECT_ID('restricao','U') IS NOT NULL DROP TABLE restricao;
IF OBJECT_ID('usuario','U') IS NOT NULL DROP TABLE [usuario];
IF OBJECT_ID('hotel','U') IS NOT NULL DROP TABLE hotel;
IF OBJECT_ID('politica','U') IS NOT NULL DROP TABLE politica;
IF OBJECT_ID('licenca','U') IS NOT NULL DROP TABLE licenca;
IF OBJECT_ID('assinatura','U') IS NOT NULL DROP TABLE assinatura;
IF OBJECT_ID('log_auth','U') IS NOT NULL DROP TABLE log_auth;
IF OBJECT_ID('codigo_verificacao','U') IS NOT NULL DROP TABLE codigo_verificacao;
IF OBJECT_ID('sessao','U') IS NOT NULL DROP TABLE sessao;
IF OBJECT_ID('usuario_auth','U') IS NOT NULL DROP TABLE usuario_auth;
IF OBJECT_ID('role_permissao','U') IS NOT NULL DROP TABLE role_permissao;
IF OBJECT_ID('permissao','U') IS NOT NULL DROP TABLE permissao;
IF OBJECT_ID('role','U') IS NOT NULL DROP TABLE [role];

-- Create base tables
CREATE TABLE [role] (
  id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
  nome NVARCHAR(150) NOT NULL UNIQUE
);

CREATE TABLE permissao (
  id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
  nome NVARCHAR(150) NOT NULL UNIQUE
);

CREATE TABLE role_permissao (
  id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
  role_id UNIQUEIDENTIFIER NOT NULL REFERENCES [role](id) ON DELETE CASCADE,
  permissao_id UNIQUEIDENTIFIER NOT NULL REFERENCES permissao(id) ON DELETE CASCADE,
  CONSTRAINT uq_role_permissao UNIQUE(role_id, permissao_id)
);

CREATE TABLE usuario_auth (
  id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
  status BIT NOT NULL DEFAULT 1,
  ultimo_login DATETIME2 NULL,
  created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  email NVARCHAR(255) NOT NULL UNIQUE,
  senha_hash NVARCHAR(255) NOT NULL
);

CREATE TABLE sessao (
  id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
  usuario_auth_id UNIQUEIDENTIFIER NOT NULL REFERENCES usuario_auth(id) ON DELETE CASCADE,
  expira_em DATETIME2 NOT NULL,
  token NVARCHAR(500) NOT NULL UNIQUE
);

CREATE TABLE codigo_verificacao (
  id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
  usuario_auth_id UNIQUEIDENTIFIER NOT NULL REFERENCES usuario_auth(id) ON DELETE CASCADE,
  expira_em DATETIME2 NOT NULL,
  codigo NVARCHAR(20) NOT NULL,
  tipo NVARCHAR(20) NOT NULL
);

CREATE TABLE log_auth (
  id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
  usuario_auth_id UNIQUEIDENTIFIER NOT NULL REFERENCES usuario_auth(id) ON DELETE CASCADE,
  data DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  acao NVARCHAR(100) NOT NULL,
  ip NVARCHAR(45)
);

CREATE TABLE assinatura (
  id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
  data_vencimento DATE NOT NULL,
  tipo NVARCHAR(50) NOT NULL,
  valor_mensal DECIMAL(10,2) NOT NULL,
  status NVARCHAR(20) NOT NULL
);

CREATE TABLE licenca (
  id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
  validade DATE NOT NULL,
  chave NVARCHAR(100) NOT NULL UNIQUE,
  empresa_nome NVARCHAR(150) NOT NULL,
  status NVARCHAR(20) NOT NULL,
  numero_licenca NVARCHAR(50) NOT NULL UNIQUE,
  ativa BIT NOT NULL DEFAULT 1,
  assinatura_id UNIQUEIDENTIFIER NULL REFERENCES assinatura(id) ON DELETE SET NULL
);

CREATE TABLE politica (
  id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
  politica_cancelamento NVARCHAR(MAX),
  horario_check_in TIME NULL,
  horario_check_out TIME NULL,
  carencia_minutos INT NULL
);

CREATE TABLE hotel (
  id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
  assinatura_id UNIQUEIDENTIFIER NULL REFERENCES assinatura(id) ON DELETE SET NULL,
  politica_id UNIQUEIDENTIFIER NULL REFERENCES politica(id) ON DELETE SET NULL,
  nome NVARCHAR(150) NOT NULL,
  moeda_local NVARCHAR(10) NOT NULL,
  endereco NVARCHAR(255),
  foto_url NVARCHAR(MAX) NULL
);

CREATE TABLE [usuario] (
  id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
  usuario_auth_id UNIQUEIDENTIFIER NULL REFERENCES usuario_auth(id) ON DELETE SET NULL,
  assinatura_id UNIQUEIDENTIFIER NULL REFERENCES assinatura(id) ON DELETE SET NULL,
  nome NVARCHAR(150) NOT NULL,
  email NVARCHAR(150),
  numero NVARCHAR(20),
  telefone NVARCHAR(20) NULL,
  tipo_usuario NVARCHAR(20) NOT NULL DEFAULT 'normal'
);

CREATE TABLE restricao (
  id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
  hotel_id UNIQUEIDENTIFIER NOT NULL REFERENCES hotel(id) ON DELETE CASCADE,
  inicio TIME NULL,
  fim TIME NULL,
  nome NVARCHAR(50) NOT NULL,
  observacao NVARCHAR(255) NULL
);

CREATE TABLE transacao (
  id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
  hotel_id UNIQUEIDENTIFIER NULL REFERENCES hotel(id) ON DELETE SET NULL,
  data DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  tipo NVARCHAR(20) NOT NULL,
  fornecedor NVARCHAR(100) NULL,
  documento NVARCHAR(50) NULL,
  categoria NVARCHAR(50) NULL,
  descricao NVARCHAR(MAX) NULL,
  valor DECIMAL(10,2) NOT NULL
);

CREATE TABLE hospede (
  id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
  data_nascimento DATE NULL,
  nome NVARCHAR(150) NOT NULL,
  email NVARCHAR(255) NULL,
  telefone NVARCHAR(50) NULL,
  cpf NVARCHAR(50) NULL,
  passaporte NVARCHAR(50) NULL,
  nacionalidade NVARCHAR(50) NULL,
  endereco NVARCHAR(255) NULL
);

CREATE TABLE dependente (
  id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
  hospede_id UNIQUEIDENTIFIER NOT NULL REFERENCES hospede(id) ON DELETE CASCADE,
  nome NVARCHAR(150) NOT NULL,
  documento NVARCHAR(100) NULL
);

CREATE TABLE andar (
  id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
  hotel_id UNIQUEIDENTIFIER NOT NULL REFERENCES hotel(id) ON DELETE CASCADE,
  numero INT NOT NULL,
  nome NVARCHAR(50) NULL
);

CREATE TABLE categoria_quarto (
  id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
  hotel_id UNIQUEIDENTIFIER NOT NULL REFERENCES hotel(id) ON DELETE CASCADE,
  descricao NVARCHAR(MAX) NULL,
  capacidade SMALLINT NOT NULL,
  nome NVARCHAR(100) NOT NULL,
  preco_diaria DECIMAL(10,2) NOT NULL
);

CREATE TABLE arquivo (
  id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
  hotel_id UNIQUEIDENTIFIER NOT NULL REFERENCES hotel(id) ON DELETE CASCADE,
  numero INT NOT NULL,
  nome NVARCHAR(100) NOT NULL
);

CREATE TABLE quarto (
  id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
  andar_id UNIQUEIDENTIFIER NOT NULL REFERENCES andar(id) ON DELETE NO ACTION,
  categoria_id UNIQUEIDENTIFIER NOT NULL REFERENCES categoria_quarto(id) ON DELETE NO ACTION,
  descricao NVARCHAR(MAX) NULL,
  capacidade SMALLINT NOT NULL,
  quantidade_camas SMALLINT NULL,
  numero NVARCHAR(50) NOT NULL,
  status NVARCHAR(20) NOT NULL
);

CREATE TABLE reserva (
  id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
  hospede_id UNIQUEIDENTIFIER NOT NULL REFERENCES hospede(id) ON DELETE NO ACTION,
  quarto_id UNIQUEIDENTIFIER NOT NULL REFERENCES quarto(id) ON DELETE NO ACTION,
  data_checkin DATETIME2 NOT NULL,
  data_checkout DATETIME2 NOT NULL,
  qtd_adultos SMALLINT NOT NULL,
  qtd_criancas SMALLINT NOT NULL DEFAULT 0,
  codigo NVARCHAR(50) NOT NULL UNIQUE,
  status NVARCHAR(50) NOT NULL,
  canal NVARCHAR(50) NULL
);

CREATE TABLE historico_reserva (
  id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
  reserva_id UNIQUEIDENTIFIER NOT NULL REFERENCES reserva(id) ON DELETE CASCADE,
  data DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  status NVARCHAR(50) NOT NULL
);

CREATE TABLE estadia (
  id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
  reserva_id UNIQUEIDENTIFIER NOT NULL REFERENCES reserva(id) ON DELETE CASCADE,
  checkin_real DATETIME2 NULL,
  checkout_real DATETIME2 NULL,
  status NVARCHAR(20) NOT NULL
);

CREATE TABLE credencial_acesso (
  id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
  reserva_id UNIQUEIDENTIFIER NULL REFERENCES reserva(id) ON DELETE CASCADE,
  hospede_id UNIQUEIDENTIFIER NULL REFERENCES hospede(id) ON DELETE CASCADE,
  dispositivo_id UNIQUEIDENTIFIER NULL,
  validade_inicio DATETIME2 NOT NULL,
  validade_fim DATETIME2 NOT NULL,
  tipo NVARCHAR(20) NOT NULL,
  codigo NVARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE log_acesso (
  id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
  credencial_id UNIQUEIDENTIFIER NOT NULL REFERENCES credencial_acesso(id) ON DELETE CASCADE,
  dispositivo_id UNIQUEIDENTIFIER NULL,
  data_hora DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  resultado NVARCHAR(50) NOT NULL
);

CREATE TABLE ordem_limpeza (
  id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
  quarto_id UNIQUEIDENTIFIER NOT NULL REFERENCES quarto(id) ON DELETE CASCADE,
  usuario_id UNIQUEIDENTIFIER NULL REFERENCES usuario_auth(id) ON DELETE SET NULL,
  data_inicio DATETIME2 NOT NULL,
  data_fim DATETIME2 NULL,
  status NVARCHAR(20) NOT NULL
);

CREATE TABLE checklist (
  id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
  ordem_id UNIQUEIDENTIFIER NOT NULL REFERENCES ordem_limpeza(id) ON DELETE CASCADE,
  concluido BIT NOT NULL DEFAULT 0,
  tipo NVARCHAR(20) NOT NULL,
  item NVARCHAR(150) NOT NULL
);

CREATE TABLE refeicao (
  id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
  nome NVARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE pedido_consumo (
  id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
  hospede_id UNIQUEIDENTIFIER NOT NULL REFERENCES hospede(id) ON DELETE CASCADE,
  refeicao_id UNIQUEIDENTIFIER NOT NULL REFERENCES refeicao(id) ON DELETE CASCADE,
  reserva_id UNIQUEIDENTIFIER NULL REFERENCES reserva(id) ON DELETE CASCADE,
  presente BIT NOT NULL DEFAULT 0,
  data DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE produto (
  id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
  nome NVARCHAR(150) NOT NULL,
  categoria NVARCHAR(150) NULL,
  preco_custo DECIMAL(10,2) NOT NULL,
  preco_venda DECIMAL(10,2) NOT NULL
);

CREATE TABLE consumo (
  id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
  estadia_id UNIQUEIDENTIFIER NOT NULL REFERENCES estadia(id) ON DELETE CASCADE,
  data DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  valor_total DECIMAL(10,2) NOT NULL DEFAULT 0
);

CREATE TABLE item_consumo (
  id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
  consumo_id UNIQUEIDENTIFIER NOT NULL REFERENCES consumo(id) ON DELETE CASCADE,
  produto_id UNIQUEIDENTIFIER NOT NULL REFERENCES produto(id) ON DELETE NO ACTION,
  data DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  valor_total DECIMAL(10,2) NOT NULL
);

CREATE TABLE fatura (
  id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
  estadia_id UNIQUEIDENTIFIER NOT NULL REFERENCES estadia(id) ON DELETE CASCADE,
  valor_total DECIMAL(10,2) NOT NULL DEFAULT 0,
  status NVARCHAR(20) NOT NULL
);

CREATE TABLE pagamento (
  id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
  fatura_id UNIQUEIDENTIFIER NOT NULL REFERENCES fatura(id) ON DELETE CASCADE,
  data_pagamento DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  valor DECIMAL(10,2) NOT NULL,
  metodo NVARCHAR(20) NOT NULL,
  status NVARCHAR(20) NOT NULL
);
