SET NOCOUNT ON;

IF OBJECT_ID('sessao','U') IS NULL
BEGIN
  CREATE TABLE sessao (
    id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    usuario_auth_id UNIQUEIDENTIFIER NOT NULL REFERENCES usuario_auth(id) ON DELETE CASCADE,
    expira_em DATETIME2 NOT NULL,
    token NVARCHAR(500) NOT NULL UNIQUE
  );
END;

IF OBJECT_ID('codigo_verificacao','U') IS NULL
BEGIN
  CREATE TABLE codigo_verificacao (
    id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    usuario_auth_id UNIQUEIDENTIFIER NOT NULL REFERENCES usuario_auth(id) ON DELETE CASCADE,
    expira_em DATETIME2 NOT NULL,
    codigo NVARCHAR(20) NOT NULL,
    tipo NVARCHAR(20) NOT NULL
  );
END;

IF OBJECT_ID('log_auth','U') IS NULL
BEGIN
  CREATE TABLE log_auth (
    id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    usuario_auth_id UNIQUEIDENTIFIER NOT NULL REFERENCES usuario_auth(id) ON DELETE CASCADE,
    data DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    acao NVARCHAR(100) NOT NULL,
    ip NVARCHAR(45)
  );
END;

IF OBJECT_ID('licenca','U') IS NULL
BEGIN
  CREATE TABLE licenca (
    id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    validade DATE NOT NULL,
    chave NVARCHAR(100) NOT NULL UNIQUE,
    empresa_nome NVARCHAR(150) NOT NULL,
    status NVARCHAR(20) NOT NULL,
    numero_licenca NVARCHAR(50) NOT NULL UNIQUE,
    ativa BIT NOT NULL DEFAULT 1,
    assinatura_id UNIQUEIDENTIFIER NULL REFERENCES assinatura(id) ON DELETE SET NULL
  );
END;

IF OBJECT_ID('usuario','U') IS NULL
BEGIN
  CREATE TABLE [usuario] (
    id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    usuario_auth_id UNIQUEIDENTIFIER NULL REFERENCES usuario_auth(id) ON DELETE SET NULL,
    assinatura_id UNIQUEIDENTIFIER NULL REFERENCES assinatura(id) ON DELETE SET NULL,
    nome NVARCHAR(150) NOT NULL,
    email NVARCHAR(150),
    numero NVARCHAR(20)
  );
END;

SELECT 'auth tables checked/created' AS resultado;
